POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento 2",
  "details": "Um Novo evento 2 para quem é apaixonado por programação",
  "maximumAttendees": 1
}

### 

POST http://localhost:3333/events/e8b1762c-8bef-4808-850f-cd768c7c57c1/attendees
Content-Type: application/json

{
  "name": "Bruno Becoski",
  "email": "bruno@rocketseat.com"
}

### 

GET http://localhost:3333/events/e8b1762c-8bef-4808-850f-cd768c7c57c1

### 

GET http://localhost:3333/attendees/5/badge

###

GET http://localhost:3333/attendees/5/check-in