# Create an event
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": 2,
  "details": "Um Novo evento 2 para quem é apaixonado por programação",
  "maximumAttendees": 1
}

### 

# Register an attendee
POST http://localhost:3333/events/e8b1762c-8bef-4808-850f-cd768c7c57c1/attendees
Content-Type: application/json

{
  "name": "Bruno Becoski",
  "email": "bruno@rocketseat.com"
}

### 

# Get an event
GET http://localhost:3333/events/e8b1762c-8bef-4808-850f-cd768c7c57c1

### 

# Get an attendee badge
GET http://localhost:3333/attendees/5/badge

###

# Check-in an attendee
GET http://localhost:3333/attendees/5/check-in

###

# Get event attendee
GET http://localhost:3333/events/cb9108f2-8d99-4d30-bfa1-bb6e3bb41da0/attendees?pageIndex=2

###

# Get events
GET http://localhost:3333/events