###

# EVENTS

###

# Create an event
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Um evento",
  "details": "Um Novo evento 2 para quem é apaixonado por programação",
  "maximumAttendees": 1,
  "startDate": "2024-07-01",
  "endDate": "2024-07-05"
}

###

# Get an event
GET http://localhost:3333/get/event/unite-summit?pageIndex=2
###

# Update an event
PUT http://localhost:3333/update/event
Content-Type: application/json

{
  "id": "ecf4ed8c-d4b7-4e38-8ff7-a9bb3e802867",
  "title": "Um Novo Evento",
  "details": "Um Novo Novo evento 2 para quem é apaixonado por programação",
  "maximumAttendees": 1,
  "startDate": "2024-07-01",
  "endDate": "2024-07-05"
}

###

# Delete an event
DELETE http://localhost:3333/delete/event/cb9108f2-8d99-4d30-bfa1-bb6e3bb41da0
###


# Get events
GET http://localhost:3333/get/events

###

# ATTENDEE

### 

# Create an attendee
POST http://localhost:3333/create/attendee
Content-Type: application/json

{
  "name": "Bru",
  "email": "bruno@rocketseat.com"
}

###

# Get an attendee
GET http://localhost:3333/get/attendee/00001
###

# Update an attendee
PUT http://localhost:3333/update/attendee
Content-Type: application/json

{
  "id": "b43c5d60-fdaf-4c74-a0f0-72f73a1ba81b",
  "name": "Bruno Alves",
  "email": "bruno@mail.com"
}

###

# Update an attendee code

GET HTTP://localhost:3333/update/attendee/code/92c14a5b-5387-48b1-866c-3c0de77c9072

###

# Delete an attendee
DELETE http://localhost:3333/delete/attendee/b2269485-de4d-4b69-aa94-ec5acf6ee903
###

# Get attendees
GET http://localhost:3333/get/attendees

###

# EVENTATTENDEE

###

# Create eventAttendee
GET http://localhost:3333/create/event/7cd6baef-8228-4290-8ac8-f71839bbb714/attendee/0c390130-aa04-4176-8294-853f57e12858

###

# Check-in eventAttendee
GET http://localhost:3333/check-in/event/3cd8d81f-bb85-413e-8108-fd08f09dc665/attendee/09b36ca2-801f-4762-a13d-b431ac87bc59

###


# Delete eventAttendee
DELETE http://localhost:3333/delete/event/ecf4ed8c-d4b7-4e38-8ff7-a9bb3e802867/attendee/26db9c58-8f20-453e-8c24-454e66ff79f9

###

# Get an attendee badge
GET http://localhost:3333/attendees/5/badge

###

# Check-in an attendee
GET http://localhost:3333/attendees/5/check-in

###

# Get attendee events
GET HTTP://localhost:3333/get/attendee/abb3b6ac-62c2-44b8-abee-58e3820dcff9/events?query=uni

###

# Get attendee events
GET HTTP://localhost:3333/get/event/af3ad086-d004-475d-96f3-2cd1fd3f52f1/attendees?pageIndex=2

###